name: Stego CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  function-unit-tests:
    runs-on: ubuntu-latest

    steps:
      # dependencies
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      # tests
      - name: Unit tests
        run: pytest

  use-case-tests:
    runs-on: ubuntu-latest

    steps:
      # dependencies
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Give scripts execution perms
        run: chmod +x tests/*.sh

      # tests
      - name: Basic tests
        run: ./tests/test-basic.sh

      - name: High capacity tests
        run: ./tests/test-high-capacity.sh

      - name: Late offset tests
        run: ./tests/test-late-offset.sh

      - name: Low detectability tests
        run: ./tests/test-low-detectability.sh

      - name: Mono channel tests
        run: ./tests/test-mono-channel.sh

