name: Stego CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Give scripts execution perms
        run: chmod +x tests/*.sh

      - name: Unit tests
        run: ./tests/unit.sh

      - name: Integration tests
        run: ./tests/integration.sh

      - name: Negative case tests
        run: ./tests/negative.sh

      - name: Property-based tests
        run: ./tests/property.sh
